# Site settings
title: Ankit Pansari
email: contact@startleventures.com  
description: Consulting Services on Microsoft PowerApps, Zoho Creator, Google App Maker. 
baseurl: "/personal-blog"
url: "www.startleventures.com"
twitter_username: pansari_a
avatar: "https://pbs.twimg.com/profile_images/829006172166369280/O_GNk30T.jpg" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Ankit Pansari" # Set default author name
      categories: "Thoughts"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
